### ISSUE TITLE
General improvement on placement of different fields

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#114] opened 2023-03-08 09:43 UTC
The old FP optimizes the space for different fields and size of fields in a better way.

Below are some scenarios that are a bit off:

1: Having a field with 2 items first sometimes only populates half of the second item
![Capture](https://user-images.githubusercontent.com/29114032/223677829-bf08899d-2729-4617-9350-69d44d8989e0.PNG)

2: The field color by Metric only has two items and it looks like it is enough room to populate the field instead
![Capture](https://user-images.githubusercontent.com/29114032/223678545-6cbe39e9-1e89-425f-b378-b648ad56cabb.PNG)

**Comment by johanlahti** [comment] 2023-03-11 09:59
The algorithm comes from the old Filter pane, implemented by @DanielS-Qlik (quite complex logic). I will assign it to you for now Daniel (if someone else wants to fix it before Monday, feel free).

**Comment by DanielS-Qlik** [comment] 2023-03-13 14:43
1. Is caused by: #63 
2. Fix: https://github.com/qlik-oss/sn-list-objects/pull/129

**Closed** 2023-03-21 07:48 UTC
Labels: bug, prio3, improvement
